export interface AnyangTourSpot {
  id: string;
  name: string;
  category: 'anyang9' | 'anyang_dong' | 'pyeongchon_hogye' | 'bisan_gwanyang' | 'seoksu_bakdal';
  categoryLabel: string;
  nineGyeongNumber?: number; // 1 ~ 9 for Anyang 9 Scenic Spots
  address: string;
  dong: string;
  lat: number;
  lng: number;
  aiSummary: string;
  description: string;
  imageUrl: string;
  imageSource: string;
  tags: string[];
  ridingTip: string;
  nearbyFacility: string;
  officialUrl?: string;
}

export const ANYANG_TOUR_DATA: AnyangTourSpot[] = [
  // ── 🏆 안양 9경 (공식 안양 9경) ──
  {
    id: 'anyang9-1',
    name: '안양예술공원',
    category: 'anyang9',
    categoryLabel: '안양 9경 (제1경)',
    nineGyeongNumber: 1,
    address: '경기도 안양시 만안구 예술공원로 일대',
    dong: '석수동',
    lat: 37.4278,
    lng: 126.9272,
    aiSummary: '삼성천을 따라 펼쳐지는 국내 최초 야외 공공예술(APAP) 프로젝트와 숲속 예술 힐링 명소!',
    description: '관악산과 삼성산 사이 삼성천 계곡을 따라 세계적 건축가와 예술가들의 조각, 건축물, 쉼터가 어우러진 안양의 대표 힐링 예술 문화 공원입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/16/thumb/p_20230209031704593q11FLK.png',
    imageSource: '안양시 문화관광',
    tags: ['#안양9경', '#제1경', '#APAP공공예술', '#삼성천계곡', '#숲속라이딩'],
    ridingTip: '삼성천 자전거길에서 예술공원 초입까지 완만하며, 숲속 그늘과 감성 카페가 많아 휴식하기 좋습니다.',
    nearbyFacility: '공기주입기 2개소, 자전거 거치대, 안양박물관/김중업박물관 인접',
    officialUrl: 'https://www.anyang.go.kr/tour/contents.do?key=670',
  },
  {
    id: 'anyang9-2',
    name: '안양천',
    category: 'anyang9',
    categoryLabel: '안양 9경 (제2경)',
    nineGyeongNumber: 2,
    address: '경기도 안양시 만안구·동안구 안양천 일원',
    dong: '안양천 전역',
    lat: 37.3912,
    lng: 126.9388,
    aiSummary: '한강까지 쾌속으로 뻗어나가는 수도권 서남부 최고의 생태하천 자전거 고속도로!',
    description: '자연형 생태하천으로 복원되어 계절마다 유채꽃, 벚꽃, 억새가 장관을 이루며 보행로와 자전거도로가 완벽히 분리된 자전거 라이더들의 성지입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/17/thumb/p_202302090318183334ECKEZ.png',
    imageSource: '안양시 문화관광',
    tags: ['#안양9경', '#제2경', '#안양천자전거길', '#생태하천', '#한강직통'],
    ridingTip: '신호등 없는 평지 무장애 전용로로 초보자부터 장거리 라이더까지 가장 안전하고 쾌적하게 달릴 수 있습니다.',
    nearbyFacility: '쌍개울 쉼터, 급속 공기주입기, 음수대, 공중화장실 상시 완비',
    officialUrl: 'https://www.anyang.go.kr/tour/contents.do?key=671',
  },
  {
    id: 'anyang9-3',
    name: '평촌중앙공원',
    category: 'anyang9',
    categoryLabel: '안양 9경 (제3경)',
    nineGyeongNumber: 3,
    address: '경기도 안양시 동안구 관평로 149',
    dong: '평촌동',
    lat: 37.3908,
    lng: 126.9575,
    aiSummary: '분수대, 잔디광장, 주말 차 없는 거리로 시민들의 사랑을 듬뿍 받는 평촌 도심의 푸른 오아시스!',
    description: '안양시 최대 도심 공원으로 수많은 조각작품, 시원한 분수대, 은행나무 산책로가 조성되어 있으며 주말에는 가족 단위 나들이객으로 활기가 넘칩니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/18/thumb/p_15BBF480-A5E8-358C-1E68-55C657A6D9AF-20200115.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양9경', '#제3경', '#평촌중앙공원', '#주말나들이', '#분수대광장'],
    ridingTip: '학의천 자전거길에서 중앙공원 램프로 바로 진입 가능하며, 주말 차 없는 거리 시간대에는 안심 라이딩이 가능합니다.',
    nearbyFacility: '중앙공원 북측/남측 공기주입기, 대형 자전거 거치대, 화장실 완비',
    officialUrl: 'https://www.anyang.go.kr/tour/contents.do?key=672',
  },
  {
    id: 'anyang9-4',
    name: '망해암 일몰',
    category: 'anyang9',
    categoryLabel: '안양 9경 (제4경)',
    nineGyeongNumber: 4,
    address: '경기도 안양시 만안구 임곡로 245 망해암',
    dong: '비산동',
    lat: 37.4082,
    lng: 126.9360,
    aiSummary: '서해 바다와 안양 시가지가 한눈에 내려다보이는 황홀한 붉은 노을 뷰포인트!',
    description: '신라 원효대사가 창건한 유서 깊은 사찰로, ‘바다를 바라본다’는 이름처럼 해 질 무렵 서해 낙조와 안양 도심의 파노라마 야경이 절경을 이룹니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/19/thumb/p_20230209031932862m4iCWU.png',
    imageSource: '안양시 문화관광',
    tags: ['#안양9경', '#제4경', '#망해암일몰', '#안양야경', '#업힐성지'],
    ridingTip: '비산동에서 올라가는 힐클라임(업힐) 코스로 라이더들의 챌린지 명소입니다. 일몰 후 야간 다운힐 시 전조등/후미등 필수!',
    nearbyFacility: '망해암 전망대 쉼터, 약수터',
    officialUrl: 'https://www.anyang.go.kr/tour/contents.do?key=673',
  },
  {
    id: 'anyang9-5',
    name: '안양 1번가',
    category: 'anyang9',
    categoryLabel: '안양 9경 (제5경)',
    nineGyeongNumber: 5,
    address: '경기도 안양시 만안구 장내로, 만안로 일대',
    dong: '안양동',
    lat: 37.4005,
    lng: 126.9215,
    aiSummary: '젊음의 에너지와 다채로운 맛집, 패션, 문화가 살아 숨 쉬는 안양 최고의 번화가!',
    description: '안양역 맞은편에 자리한 대표적인 쇼핑·문화·먹거리 거리로, 만안구의 역사와 젊은이들의 활기찬 일상이 교차하는 중심 상권입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/20/thumb/p_20230209032016204sdeCad.png',
    imageSource: '안양시 문화관광',
    tags: ['#안양9경', '#제5경', '#안양일번가', '#젊음의거리', '#맛집탐방'],
    ridingTip: '안양역 및 안양천 진입로와 가까우며, 보행자가 많으므로 자전거에서 내려 안전하게 거치 후 도보 이용을 권장합니다.',
    nearbyFacility: '안양역 환승센터 자전거 보관소, 기계식 거치대, 중앙시장 연결로',
    officialUrl: 'https://www.anyang.go.kr/tour/contents.do?key=674',
  },
  {
    id: 'anyang9-6',
    name: '수리산성지',
    category: 'anyang9',
    categoryLabel: '안양 9경 (제6경)',
    nineGyeongNumber: 6,
    address: '경기도 안양시 만안구 병목안로 394',
    dong: '안양동',
    lat: 37.3775,
    lng: 126.9030,
    aiSummary: '수리산 골짜기 고요함 속에 깃든 우리나라 두 번째 사제 최양업 신부의 역사와 숨결!',
    description: '천주교 박해 시절 교우촌이 형성되었던 유서 깊은 성지로, 순교자 최경환 성인의 묘소와 고즈넉한 숲길이 평온한 사색의 시간을 선사합니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/21/thumb/p_20220504110521911YvDW1i.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양9경', '#제6경', '#수리산성지', '#최경환성지', '#피톤치드숲길'],
    ridingTip: '병목안 시민공원을 지나 완만한 오르막 숲길을 따라 오르면 맑은 공기와 힐링을 만끽할 수 있습니다.',
    nearbyFacility: '수리산 성지 쉼터, 병목안 공영주차장 인근 정비 시설',
    officialUrl: 'https://www.anyang.go.kr/tour/contents.do?key=675',
  },
  {
    id: 'anyang9-7',
    name: '평촌1가 문화의 거리',
    category: 'anyang9',
    categoryLabel: '안양 9경 (제7경)',
    nineGyeongNumber: 7,
    address: '경기도 안양시 동안구 4호선 범계역 2번출구 일대',
    dong: '호계동',
    lat: 37.3900,
    lng: 126.9520,
    aiSummary: '범계역을 중심으로 트렌디한 카페, 쇼핑, 문화 행사가 끊이지 않는 동안구 대표 로데오거리!',
    description: '범계역 역세권 광장과 차 없는 보행자 전용도로로 조성되어 있어 야외 버스킹, 팝업 문화 이벤트와 다양한 미식을 즐길 수 있는 안양 핫플레이스입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/22/thumb/p_20210108105648218pUKkxf.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양9경', '#제7경', '#평촌1가', '#범계로데오', '#문화의거리'],
    ridingTip: '학의천 자전거길에서 범계역 방면 자전거도로를 통해 빠르게 접근 가능합니다. 광장 진입 시 자전거 거치 후 이용하세요.',
    nearbyFacility: '범계역 1/2번 출구 자전거 보관소, 롯데백화점 자전거 쉼터',
    officialUrl: 'https://www.anyang.go.kr/tour/contents.do?key=676',
  },
  {
    id: 'anyang9-8',
    name: '병목안 시민공원',
    category: 'anyang9',
    categoryLabel: '안양 9경 (제8경)',
    nineGyeongNumber: 8,
    address: '경기도 안양시 만안구 병목안로 215',
    dong: '안양동',
    lat: 37.3872,
    lng: 126.9145,
    aiSummary: '웅장한 초대형 인공폭포와 철도 자갈 채석장의 역사가 친환경 생태공원으로 부활한 곳!',
    description: '수리산 자락 병목 형태의 아늑한 지형에 조성된 공원으로, 높이 65m의 웅장한 인공폭포와 어린이 놀이터, 캠핑장이 어우러져 사계절 나들이로 최고입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/23/thumb/p_20210108015831898bjr1S2.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양9경', '#제8경', '#병목안시민공원', '#인공폭포', '#수리산캠핑'],
    ridingTip: '안양천 삼덕공원을 지나 수리산 방향 자전거도로로 상쾌하게 라이딩할 수 있는 완만한 힐링 코스입니다.',
    nearbyFacility: '병목안공원 입구 공기주입기, 자전거 거치대, 화장실, 매점',
    officialUrl: 'https://www.anyang.go.kr/tour/contents.do?key=677',
  },
  {
    id: 'anyang9-9',
    name: '만안교',
    category: 'anyang9',
    categoryLabel: '안양 9경 (제9경)',
    nineGyeongNumber: 9,
    address: '경기도 안양시 만안구 석수동 679',
    dong: '석수동',
    lat: 37.4305,
    lng: 126.9100,
    aiSummary: '조선 정조대왕의 효심과 조선 후기 대표 석교 건축미가 빛나는 경기도 유형문화재 제38호!',
    description: '정조대왕이 아버지 사도세자의 능을 참배하러 가기 위해 1795년 축조한 아름다운 7련 홍예 석교로, 견고하고 웅장한 아치형 돌다리의 미학을 자랑합니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/19/thumb/p_74C657E2-741C-120D-39E4-BACBDEA3A796-20191126.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양9경', '#제9경', '#만안교', '#정조대왕효심', '#조선역사유적'],
    ridingTip: '안양천 본류 자전거도로와 바로 맞닿아 있어 라이딩 중 언제든 다리 위로 올라와 고풍스러운 석교를 감상할 수 있습니다.',
    nearbyFacility: '만안교 쉼터, 안양천 직결 자전거 램프, 벤치',
    officialUrl: 'https://www.anyang.go.kr/tour/contents.do?key=678',
  },

  // ── 📍 안양동 명소 ──
  {
    id: 'dong-anyang-1',
    name: '수리산 산림욕장',
    category: 'anyang_dong',
    categoryLabel: '안양동',
    address: '경기도 안양시 만안구 안양동 산101-1',
    dong: '안양동',
    lat: 37.3835,
    lng: 126.9080,
    aiSummary: '울창한 피톤치드 잣나무 숲과 맑은 공기를 품은 수리산 자락의 천연 산림 휴양지!',
    description: '소나무, 잣나무가 울창하여 삼림욕에 최적이며, 숲길을 따라 산책로와 체육시설, 쉼터가 잘 조성되어 맑은 자연을 호흡할 수 있습니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/31/thumb/p_CBB92697-DBB4-7DEC-0CAA-30FE1E1359FA-20191127.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#수리산산림욕장', '#피톤치드', '#피크닉', '#힐링숲'],
    ridingTip: '병목안로 방면에서 진입 가능하며, 숲속 진입 전 자전거를 거치하고 가벼운 트레킹을 즐기기 좋습니다.',
    nearbyFacility: '산림욕장 입구 거치대, 화장실, 약수터',
  },
  {
    id: 'dong-anyang-2',
    name: '안양아트센터',
    category: 'anyang_dong',
    categoryLabel: '안양동',
    address: '경기도 안양시 만안구 문예로36번길 16',
    dong: '안양동',
    lat: 37.3828,
    lng: 126.9325,
    aiSummary: '고품격 클래식 공연과 전시, 뮤지컬을 만나는 만안구의 대표 문화예술 복합 전당!',
    description: '관악홀, 수리홀, 갤러리 미담을 갖춘 복합 문화예술 공간으로 사계절 수준 높은 기획 공연과 예술 아카데미가 열립니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/31/thumb/p_D1B33EF4-B1B1-B29D-3D68-0EA7F4BC0283-20191127.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양아트센터', '#문화예술', '#공연전시', '#명학역'],
    ridingTip: '명학역 및 수리산로 자전거도로와 연계되어 라이딩 중 전시를 관람하기에 제격입니다.',
    nearbyFacility: '안양아트센터 광장 자전거 거치대, 공기주입기, 지하주차장',
  },
  {
    id: 'dong-anyang-3',
    name: '안양중앙시장',
    category: 'anyang_dong',
    categoryLabel: '안양동',
    address: '경기도 안양시 만안구 안양로291번길 34',
    dong: '안양동',
    lat: 37.3985,
    lng: 126.9240,
    aiSummary: '순대곱창골목과 김밥, 옛날 통닭의 성지! 정이 넘치는 경기 최대 규모 전통시장!',
    description: '1926년 개장 이래 안양 서민들의 입맛을 책임져 온 전통시장으로, 유명한 순대곱창골목과 비빔밥, 떡볶이 등 푸짐한 먹거리가 가득합니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/31/thumb/p_CE91455F-8AB0-AA7A-F26A-039213A45DCF-20191127.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양중앙시장', '#순대곱창골목', '#전통시장', '#가성비맛집'],
    ridingTip: '안양천에서 삼덕공원 쪽으로 빠져나오면 도보 3분 거리입니다. 라이딩 보급식이나 든든한 식사로 추천합니다.',
    nearbyFacility: '중앙시장 공영주차장 자전거 보관소, 삼덕공원 화장실',
  },
  {
    id: 'dong-anyang-4',
    name: '삼덕공원',
    category: 'anyang_dong',
    categoryLabel: '안양동',
    address: '경기도 안양시 만안구 병목안로 40',
    dong: '안양동',
    lat: 37.3965,
    lng: 126.9205,
    aiSummary: '삼덕제지 공장 터를 시민의 품으로 기부채납하여 탄생한 도심 속 따스한 휴식 공원!',
    description: '고(故) 전재준 회장이 기부한 삼덕제지 부지에 조성된 공원으로, 굴뚝 조형물과 잔디마당, 물놀이 분수, 산책로가 평화롭습니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/31/thumb/p_3E8C2906-7657-D558-692A-E42C174FE581-20191127.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#삼덕공원', '#기부문화', '#도심공원', '#물놀이터'],
    ridingTip: '안양천과 수리산 자전거길을 잇는 관문 역할을 하며, 넓은 광장에서 잠시 스트레칭하기 좋습니다.',
    nearbyFacility: '삼덕공원 지하주차장 상단 공기주입기, 음수대, 화장실',
  },
  {
    id: 'dong-anyang-5',
    name: '돌석도예박물관',
    category: 'anyang_dong',
    categoryLabel: '안양동',
    address: '경기도 안양시 만안구 병목안로 288',
    dong: '안양동',
    lat: 37.3812,
    lng: 126.9078,
    aiSummary: '한국 전통 도자기의 숨결과 현대 도예 예술을 한눈에 감상하는 프라이빗 도예 명소!',
    description: '수리산 자락에 자리하여 흙과 불이 빚어낸 도예 명작들과 도자기 제작 체험, 차 한 잔의 여유를 즐길 수 있는 문화 공간입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/31/thumb/p_12D1EEA1-FBF3-D51D-9614-629756028886-20191220.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#돌석도예박물관', '#전통도예', '#도자기체험', '#수리산문화'],
    ridingTip: '병목안로 숲길을 따라 여유롭게 오르막 라이딩을 즐기며 방문하기 좋습니다.',
    nearbyFacility: '박물관 마당 쉼터, 병목안 주차장 인근 편의시설',
  },
  {
    id: 'dong-anyang-6',
    name: '안양지하상가',
    category: 'anyang_dong',
    categoryLabel: '안양동',
    address: '경기도 안양시 만안구 만안로 232 일대',
    dong: '안양동',
    lat: 37.4015,
    lng: 126.9230,
    aiSummary: '국내 최대 규모를 자랑하는 패션·쇼핑의 메카! 날씨 걱정 없이 둘러보는 지하 쇼핑 스트리트!',
    description: '안양역과 직통 연결되는 초대형 지하쇼핑몰로, 수백 개의 패션, 잡화, 액세서리 매장이 모여 있어 트렌디한 쇼핑을 즐길 수 있습니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/31/thumb/p_1E3E4D13-1FE5-8EC7-DCB9-E3169B9CE2E6-20191127.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양지하상가', '#쇼핑천국', '#안양역', '#트렌드패션'],
    ridingTip: '안양역 1번 출구 자전거 보관소에 안전하게 거치 후 지하로 바로 내려갈 수 있습니다.',
    nearbyFacility: '안양역 1호선 기계식 자전거 주차타워, 엘리베이터',
  },

  // ── 📍 평촌동 / 호계동 명소 ──
  {
    id: 'dong-pyeongchon-1',
    name: '범계 로데오',
    category: 'pyeongchon_hogye',
    categoryLabel: '평촌/호계동',
    address: '경기도 안양시 동안구 평촌대로223번길 일대',
    dong: '호계동',
    lat: 37.3905,
    lng: 126.9535,
    aiSummary: '안양 동안구 최대 상권! 감성 카페, 프리미엄 다이닝, 보행자 전용 로데오거리!',
    description: '범계역 1·2번 출구를 중심으로 깔끔하게 정비된 로데오 스트리트로, 밤낮으로 젊은이들과 직장인들의 약속 장소로 붐빕니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/34/thumb/p_F0D045C7-48B6-7119-8022-7F45783F41B0-20191128.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#범계로데오', '#핫플레이스', '#카페투어', '#평촌중심가'],
    ridingTip: '평촌대로 자전거도로가 잘 정비되어 있으며, 평촌중앙공원과도 직결됩니다.',
    nearbyFacility: '범계역 자전거 거치대, 롯데백화점 평촌점 편의시설',
  },
  {
    id: 'dong-pyeongchon-2',
    name: '자유 공원',
    category: 'pyeongchon_hogye',
    categoryLabel: '평촌/호계동',
    address: '경기도 안양시 동안구 평촌대로 76',
    dong: '호계동',
    lat: 37.3775,
    lng: 126.9650,
    aiSummary: '자유센터, 론볼경기장, 축구장, 어린이교통공원이 모여 있는 다채로운 레포츠 힐링 공원!',
    description: '호계동 주택가에 인접한 울창한 공원으로 안양시 자유센터, 축구전용구장, 론볼장, 평촌아트홀이 위치해 가족 레저에 최적입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/34/thumb/p_E06BC5C9-B45C-03B9-DC0A-173082BEC461-20191128.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#자유공원', '#평촌아트홀', '#어린이교통공원', '#가족레포츠'],
    ridingTip: '평촌대로를 따라 완만한 평지길로 진입할 수 있으며 공원 내부 순환 산책로가 넓습니다.',
    nearbyFacility: '평촌아트홀 앞 공기주입기, 화장실, 약수터',
  },
  {
    id: 'dong-pyeongchon-3',
    name: '평촌 먹거리촌',
    category: 'pyeongchon_hogye',
    categoryLabel: '평촌/호계동',
    address: '경기도 안양시 동안구 귀인로190번길 일대 (귀인동)',
    dong: '평촌동',
    lat: 37.3860,
    lng: 126.9690,
    aiSummary: '정갈한 한정식부터 감성 고깃집, 이국적인 디저트까지 미식가들이 즐겨 찾는 대표 음식 테마거리!',
    description: '귀인동 현대홈타운 인근에 100여 개가 넘는 유명 맛집과 카페가 밀집한 특화 음식거리로, 쾌적하고 조용한 식사를 즐길 수 있습니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/34/thumb/p_9DC3E661-D3A5-35EC-0FE4-093BA808A0EB-20191128.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#평촌먹거리촌', '#귀인동맛집', '#미식라이딩', '#정갈한맛집'],
    ridingTip: '학의천 자전거길 포일교/백운교 방향에서 남쪽으로 진입하기 편하며 주말 식사 코스로 인기입니다.',
    nearbyFacility: '먹거리촌 공영주차장, 편의점 및 쉼터',
  },
  {
    id: 'dong-pyeongchon-4',
    name: '안양 농수산물도매시장',
    category: 'pyeongchon_hogye',
    categoryLabel: '평촌/호계동',
    address: '경기도 안양시 동안구 흥안대로 313',
    dong: '평촌동',
    lat: 37.3920,
    lng: 126.9745,
    aiSummary: '산지 직송 싱싱한 과일과 활어회, 제철 농수산물을 착한 가격에 만나는 활기찬 도매시장!',
    description: '수산동, 청과동, 채소동으로 구성된 대형 공영 도매시장으로, 싱싱한 활어회와 제철 과일을 맛보고 구매할 수 있는 활력 넘치는 공간입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/34/thumb/p_081FDAFE-88ED-DE5A-46A7-92B38F307B6F-20191128.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양농수산물시장', '#활어회센타', '#싱싱한과일', '#산지직송'],
    ridingTip: '학의천 자전거길에서 흥안대로 방면 진입로를 이용하면 자전거로 쉽게 접근할 수 있습니다.',
    nearbyFacility: '도매시장 입구 자전거 보관소, 고객 편의시설, 화장실',
  },

  // ── 📍 비산동 / 관양동 명소 ──
  {
    id: 'dong-bisan-1',
    name: '종합운동장 (안양종합운동장)',
    category: 'bisan_gwanyang',
    categoryLabel: '비산/관양동',
    address: '경기도 안양시 동안구 비산동 1023 (비산로 156)',
    dong: '비산동',
    lat: 37.4055,
    lng: 126.9475,
    aiSummary: 'FC안양 축구와 정관장 레드부스터스 농구의 열기가 뜨거운 안양 스포츠의 메카!',
    description: '주경기장, 실내체육관, 빙상장, 수영장, 인라인롤러장을 완비한 초대형 시민 체육단지로 다양한 스포츠 경기와 생활체육을 즐길 수 있습니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/32/thumb/p_20260504013035382STNBTt.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양종합운동장', '#FC안양', '#스포츠메카', '#빙상장'],
    ridingTip: '비산교 자전거길에서 비산로 전용 자전거도로로 바로 연결되며, 단지 내 통로가 넓어 안전합니다.',
    nearbyFacility: '실내체육관 앞 태양광 급속 공기주입기, 음수대, 대형 거치대',
  },
  {
    id: 'dong-bisan-2',
    name: '동편 마을',
    category: 'bisan_gwanyang',
    categoryLabel: '비산/관양동',
    address: '경기도 안양시 동안구 동편로 일대',
    dong: '관양동',
    lat: 37.4060,
    lng: 126.9805,
    aiSummary: '유럽풍 테라스와 울창한 가로수길, 감각적인 브런치 카페가 즐비한 안양의 대표 카페거리!',
    description: '관악산 자락 아래 이국적인 건물들과 초록빛 공원이 어우러진 주택형 특화단지로, 드라마 촬영지와 라이더들의 브런치 명소로 유명합니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/32/thumb/p_20260504021437897gkupgF.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#동편마을', '#카페거리', '#브런치맛집', '#드라마촬영지', '#감성라이딩'],
    ridingTip: '학의천 자전거길 인덕원역 부근에서 동편마을 수변길로 진입하면 여유로운 카페 라이딩이 완성됩니다.',
    nearbyFacility: '동편마을 중앙공원 자전거 거치대, 공중화장실, 브런치 카페 테라스 거치',
  },
  {
    id: 'dong-bisan-3',
    name: '학의천',
    category: 'bisan_gwanyang',
    categoryLabel: '비산/관양동',
    address: '경기도 안양시 동안구 관양동·비산동 일원',
    dong: '관양동',
    lat: 37.3970,
    lng: 126.9580,
    aiSummary: '백로와 잉어가 뛰노는 맑은 물과 시원한 버드나무 그늘이 이어지는 수변 힐링 명품길!',
    description: '안양천 쌍개울 합수부에서 의왕 백운호수까지 이어지는 4.5km 청정 하천으로, 전 구간 평지 전용로와 수변 생태 관찰대가 잘 갖춰져 있습니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/17/thumb/p_202302090318183334ECKEZ.png',
    imageSource: '안양시 문화관광',
    tags: ['#학의천자전거길', '#쌍개울합수부', '#버드나무그늘', '#백운호수연결'],
    ridingTip: '평지 100% 무장애 도로로 바람 저항이 적어 온 가족 및 입문 라이더에게 가장 추천하는 코스입니다.',
    nearbyFacility: '쌍개울 문화광장 쉼터, 학의천 공기주입기 3개소, 음수대',
  },
  {
    id: 'dong-bisan-4',
    name: '안양예절교육관',
    category: 'bisan_gwanyang',
    categoryLabel: '비산/관양동',
    address: '경기도 안양시 동안구 비산로 48',
    dong: '비산동',
    lat: 37.4020,
    lng: 126.9405,
    aiSummary: '고즈넉한 한옥 마당에서 전통 다도와 예절, 전통혼례 문화를 체험하는 도심 속 한옥 배움터!',
    description: '전통 한옥 양식으로 지어져 사계절 단아한 풍경을 자랑하며, 다도 체험과 전통 예절 강좌, 전통 놀이를 통해 힐링할 수 있는 공간입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/35/thumb/p_F59FB7CE-4930-0A11-315D-AFFDBBF84D7F-20191212.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양예절교육관', '#전통한옥', '#다도체험', '#전통혼례', '#고즈넉한풍경'],
    ridingTip: '비산동 안양천 제방도로에서 비산초교 방향으로 완만하게 진입할 수 있습니다.',
    nearbyFacility: '예절교육관 앞 자전거 거치 공간, 주차장, 쉼터',
  },

  // ── 📍 석수동 / 박달동 명소 ──
  {
    id: 'dong-seoksu-1',
    name: '김중업 건축 박물관',
    category: 'seoksu_bakdal',
    categoryLabel: '석수/박달동',
    address: '경기도 안양시 만안구 예술공원로103번길 4',
    dong: '석수동',
    lat: 37.4265,
    lng: 126.9245,
    aiSummary: '한국 근대 건축의 거장 김중업 선생의 건축 미학과 유유산업 공장 재생의 감동!',
    description: '한국 건축계의 거장 고(故) 김중업 선생이 설계한 유유산업 공장 건물을 리모델링하여 건축의 역사와 아름다움을 전시하는 국내 유일의 건축박물관입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/33/thumb/p_F3F3512B-51D8-B962-F4AF-32836CEC35FE-20191127.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#김중업건축박물관', '#근대건축유산', '#안양예술공원', '#건축미학'],
    ridingTip: '안양예술공원 입구에 위치해 평지 자전거길로 편안하게 찾아갈 수 있습니다.',
    nearbyFacility: '박물관 정문 자전거 거치대, 화장실, 카페 더 테라스',
  },
  {
    id: 'dong-seoksu-2',
    name: '생태 이야기관 (안양천생태이야기관)',
    category: 'seoksu_bakdal',
    categoryLabel: '석수/박달동',
    address: '경기도 안양시 만안구 석수로 379',
    dong: '석수동',
    lat: 37.4225,
    lng: 126.9015,
    aiSummary: '오염되었던 안양천이 생명의 하천으로 다시 살아난 감동의 기적을 체험하는 환경 생태 배움터!',
    description: '안양천의 역사, 생태계 복원 과정, 서식하는 다양한 조류와 물고기들을 3D 영상과 인터랙티브 체험으로 배울 수 있는 생태 교육관입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/33/thumb/p_E977EE2B-DCAD-9C57-C0BA-94FB8C110EE5-20191212.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양천생태이야기관', '#생태복원기적', '#환경교육', '#어린이나들이'],
    ridingTip: '안양천 본류 자전거도로와 바로 접해 있어 라이딩 중 아이들과 함께 들르기 가장 좋은 휴식처입니다.',
    nearbyFacility: '생태이야기관 앞 자전거 공기주입기, 음수대, 휴게 벤치, 화장실',
  },
  {
    id: 'dong-seoksu-3',
    name: '삼막 마을 (삼막맛거리촌)',
    category: 'seoksu_bakdal',
    categoryLabel: '석수/박달동',
    address: '경기도 안양시 만안구 삼막로 일대',
    dong: '석수동',
    lat: 37.4420,
    lng: 126.9210,
    aiSummary: '삼막사 계곡 맑은 물과 어우러진 백숙, 쌈밥, 보양식 맛집이 모인 수도권 대표 맛거리촌!',
    description: '삼성산 삼막사 진입로에 형성된 안양의 명물 음식문화 특화거리로, 라이딩 후 피로를 풀어줄 건강 보양식과 야외 정원 카페가 즐비합니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/36/thumb/p_7A117585-BDA2-5BD1-ECDE-2AD91A456C66-20200116.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#삼막마을', '#삼막맛거리촌', '#보양식맛집', '#삼성산계곡', '#라이더성지'],
    ridingTip: '경수대로 자전거길 및 삼성천 코스에서 완만한 오르막으로 연결됩니다.',
    nearbyFacility: '삼막마을 공영주차장, 각 식당 전용 자전거 거치대',
  },
  {
    id: 'dong-seoksu-4',
    name: '안양박물관',
    category: 'seoksu_bakdal',
    categoryLabel: '석수/박달동',
    address: '경기도 안양시 만안구 예술공원로103번길 4',
    dong: '석수동',
    lat: 37.4262,
    lng: 126.9248,
    aiSummary: '선사시대 유물부터 중초사지 당간지주, 안양사지의 깊은 천년 역사를 품은 시립 박물관!',
    description: '보물 제4호 중초사지 당간지주와 삼층석탑이 보존된 역사 유적지에 위치하여 안양의 뿌리와 역사를 한눈에 조망할 수 있는 공간입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/33/thumb/p_449122A4-E541-0B40-3F96-D5A67C9F0139-20191127.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양박물관', '#중초사지당간지주', '#천년역사', '#보물제4호'],
    ridingTip: '김중업건축박물관과 같은 단지에 있어 한 번에 두 곳의 역사·문화를 모두 둘러볼 수 있습니다.',
    nearbyFacility: '박물관 복합 문화단지 자전거 거치대, 화장실, 엘리베이터',
  },
  {
    id: 'dong-seoksu-5',
    name: '서울대 관악 수목원',
    category: 'seoksu_bakdal',
    categoryLabel: '석수/박달동',
    address: '경기도 안양시 만안구 예술공원로 280 (석수동 산22-1)',
    dong: '석수동',
    lat: 37.4330,
    lng: 126.9380,
    aiSummary: '수십 년간 원형 그대로 보존된 1,100여 종 식물의 보고! 비밀의 숲 생태 수목원!',
    description: '관악산 남쪽 기슭에 위치한 우리나라 최초의 수목원으로, 희귀 수목과 맑은 계곡이 원시림처럼 울창하여 안양예술공원 최상류의 비경을 선사합니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/33/thumb/p_1671149A-BE65-14EB-26EB-182F4A33F392-20191127.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#서울대관악수목원', '#비밀의숲', '#희귀식물원', '#계곡트레킹'],
    ridingTip: '안양예술공원 최상류 종점에 위치하며, 수목원 내부 진입은 도보 보행자만 가능하므로 정문 거치대를 이용하세요.',
    nearbyFacility: '수목원 정문 자전거 거치대, 관리소, 간이화장실',
  },
  {
    id: 'dong-seoksu-6',
    name: '관악산 둘레길 (안양구간)',
    category: 'seoksu_bakdal',
    categoryLabel: '석수/박달동',
    address: '경기도 안양시 만안구 석수동 관악산자락길 일대',
    dong: '석수동',
    lat: 37.4385,
    lng: 126.9290,
    aiSummary: '관악산 숲속 피톤치드와 맑은 약수터를 따라 걷는 친환경 명품 둘레길 코스!',
    description: '석수역에서 시작하여 안양예술공원, 망해암까지 이어지는 둘레길로, 경사가 완만하고 숲 그늘이 시원하여 사계절 힐링 트레킹에 안성맞춤입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/33/thumb/p_2F3BD2FF-D6FA-58C4-5D96-5866813B7B18-20191127.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#관악산둘레길', '#안양자락길', '#숲속트레킹', '#석수역출발'],
    ridingTip: '석수역 1호선 자전거길과 연계하여 자전거 라이딩과 숲길 산책을 함께 즐기기에 최적입니다.',
    nearbyFacility: '석수역 자전거 보관소, 둘레길 입구 흙먼지털이기, 안내센터',
  },
  {
    id: 'dong-seoksu-7',
    name: '안양새물공원',
    category: 'seoksu_bakdal',
    categoryLabel: '석수/박달동',
    address: '경기도 안양시 만안구 박달로 381',
    dong: '박달동',
    lat: 37.4110,
    lng: 126.8990,
    aiSummary: '하수처리장을 지하화하고 지상에 거대한 테니스장, 축구장, 산책공원을 조성한 친환경 명소!',
    description: '광명역 KTX 인근 박달동에 조성된 대규모 친환경 체육 생태공원으로, 파크골프장, 풋살장, 넓은 잔디마당이 펼쳐져 여유로운 라이딩이 가능합니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/33/thumb/p_D4C8B82B-C202-AE2E-B666-874C19D4EE9D-20191008.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#안양새물공원', '#친환경생태공원', '#파크골프', '#박달동명소'],
    ridingTip: '안양천 하류 박달교 부근에서 새물공원 전용 도로로 안전하게 진입할 수 있습니다.',
    nearbyFacility: '새물공원 관리동 자전거 거치대, 화장실, 음수대',
  },
  {
    id: 'dong-seoksu-8',
    name: '삼막애견공원',
    category: 'seoksu_bakdal',
    categoryLabel: '석수/박달동',
    address: '경기도 안양시 만안구 석수동 58-2 (삼막IC 부근)',
    dong: '석수동',
    lat: 37.4450,
    lng: 126.9180,
    aiSummary: '반려견과 주인이 목줄 없이 마음껏 뛰노는 전국 최대 규모의 안양시 직영 반려동물 테마공원!',
    description: '대형견·중소형견 전용 놀이터, 음수대, 격리펜스, 그늘막 쉼터를 완비하여 반려인과 반려견 모두에게 사랑받는 무료 애견 전용 공원입니다.',
    imageUrl: 'https://www.anyang.go.kr/DATA/tour/33/thumb/p_959F528A-893C-EB2E-BB7E-1CA8DA0F4369-20191008.jpg',
    imageSource: '안양시 문화관광',
    tags: ['#삼막애견공원', '#반려견놀이터', '#천연잔디운동장', '#무료입장'],
    ridingTip: '삼성천 자전거길에서 삼막IC 방면으로 올라오면 넓은 전용 주차장과 자전거 거치대를 만날 수 있습니다.',
    nearbyFacility: '애견공원 안내소, 전용 음수대, 자전거 거치대, 화장실',
  },
];
